version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - monitoring_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '${PROMETHEUS_PORT}:9090'
    networks:
      - monitoring_network
    depends_on:
      - postgres_exporter
      - redis_exporter

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: always
    ports:
      - '${POSTGRES_EXPORTER_PORT}:9187'
    networks:
      - monitoring_network
    depends_on:
      - postgres

  redis_exporter:
    image: oliver006/redis_exporter:latest
    restart: always
    ports:
      - '${REDIS_EXPORTER_PORT}:9121'
    networks:
      - monitoring_network
    depends_on:
      - redis

networks:
  monitoring_network:
