version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '${PROMETHEUS_PORT}:9090'
    networks:
      - monitoring_network
    depends_on:
      - postgres-exporter
      - node-exporter

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: always
    ports:
      - '${POSTGRES_EXPORTER_PORT}:9187'
    networks:
      - monitoring_network
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - '${GRAFANA_PORT}:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/datasources:/var/lib/grafana/provisioning/datasources
      - ./grafana/provisioning/auth:/etc/grafana/provisioning/auth
      - ./grafana/provisioning/dashboards:/var/lib/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  node-exporter:
    hostname: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - '${NODE_EXPORTER_PORT}:9100'
    networks:
      - monitoring_network

  loki:
    image: grafana/loki:latest
    ports:
      - '${LOKI_PORT}:3100'
    networks:
      - monitoring_network
    volumes:
      - ./loki/config/loki-local-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    networks:
      - monitoring_network
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/log:/var/log
      - ./promtail/config/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

networks:
  monitoring_network:

volumes:
  grafana_data:
  prometheus_data:
