services:
  node-exporter:
    hostname: node-exporter
    image: prom/node-exporter:latest
    ports:
      - '${NODE_EXPORTER_PORT}:9100'
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '${PROMETHEUS_PORT}:9090'
    networks:
      - monitoring_network
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - '${GRAFANA_PORT}:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring_network
    depends_on:
      - prometheus

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
